services:
  backend:
    build:
      context: .
      dockerfile: .Dockerfile
    image: test-mouts-backend/backend:v1.0
    ports:
      - "8080:80"
    environment:
    - ConnectionStrings__Default=host.docker.internal,1433;Database=Crud_Example;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=True;TrustServerCertificate=True;
    - CORS__AllowedOrigins=http://localhost:5173,http://localhost:3000
